//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileNumber
    {
        public int MobileID { get; set; }
        public int MobileContactID { get; set; }
        public Nullable<int> MobileNumber1 { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
